config/routes.rb
Rails.application.routes.draw do
	devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
	devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
    }

    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    post '/callback' => 'linebot#callback'
    get 'users/twitter_new' => 'users#twitter_new', as: 'user_twitter_new'
    patch 'users/twitter_update/:id' => 'users#twitter_update', as: 'user_twitter_update'
    resources :users, only: [:show, :edit, :update]
    resources :events, only: [:show, :index] do
        get '/timetable' => 'events#timetable', as: 'timetable'
        get '/confirm' => 'events#confirm', as: 'confirm'
        get '/afterparty' => 'after_parties#show', as: 'party'
        resources :event_users, only: [:index, :create, :update, :destroy]
        resources :entry_tables, only: [:update, :destroy]
        post 'musics/new_confirm' => 'musics#new_confirm', as: 'music_new_confirm'
        patch 'musics/:id/edit_confirm' => 'musics#edit_confirm', as: 'music_edit_confirm'
        resources :musics, except: [:index] do
            resources :music_comments, only: [:create, :destroy]
            post '/lyrics/new_confirm' => 'lyrics#new_confirm', as: 'lyric_new_confirm'
            patch '/lyrics/:id/edit_confirm' => 'lyrics#edit_confirm', as: 'lyric_edit_confirm'
            patch '/lyrics/select_confirm' => 'lyrics#select_confirm', as: 'lyric_select_confirm'
            patch '/lyrics/select' => 'lyrics#select', as: 'lyric_select'
            resources :lyrics, only: [:new, :create, :edit, :update, :destroy]
        end
        post 'event_threads/confirm' => 'event_threads#confirm', as: 'threads_confirm'
        resources :event_threads, only: [:new, :create, :show, :update, :destroy] do
            resources :event_thread_comments, only: [:create, :destroy]
        end
    end

    namespace :admin do
      root 'homes#top'
    end

    namespace :admin do
      post 'events/new_confirm' => 'events#new_confirm', as: 'new_confirm'
      resources :events do
        get '/timetable' => 'events#timetable', as: 'timetable'
        patch '/timetable/releace' => 'events#timetable_releace', as: 'timetable_releace'
        patch '/timetable/sort' => 'events#sort'
        patch 'edit_confirm' => 'events#edit_confirm', as: 'edit_confirm'
        resources :entry_tables, only: [:update]
        resources :event_users, only: [:index, :update, :destroy]
      end
    end

    namespace :admin do
      resources :users, only: [:index, :show, :edit, :update]
    end
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :musics, -> { order(position: :asc) }, dependent: :destroy
	has_many :event_users, dependent: :destroy
	has_many :parts, dependent: :destroy
	has_many :part_tables, dependent: :destroy
	has_one :after_party, dependent: :destroy
	attachment :image

	accepts_nested_attributes_for :part_tables, allow_destroy: true, update_only: true
	accepts_nested_attributes_for :parts, allow_destroy: true, update_only: true
	accepts_nested_attributes_for :after_party, allow_destroy: true, update_only: true

    validates :event_name, presence: true, uniqueness: true
	validates :friendly_url, length: { in: 3..20 },
                         uniqueness: true,
                         format: { with: /\A[\w@-]*[A-Za-z][\w@-]*\z/ }
	validates :date, presence: true
	validates :meeting_time, presence: true
	validates :start_time, presence: true
	validates :finish_time, presence: true
	validates :place, presence: true
	validates :performance_fee, presence: true
	validates :visit_fee, presence: true


	include FriendlyId
  		friendly_id :friendly_url

  	def create_part
  		self.part_tables.each do |part_table|
	      	m = part_table.count
	      	n = 1
	      	m.times do
		        @part = self.parts.build
		        if m == 1
		          	@part.part_name = part_table.part_name
		        elsif m > 1
		          	@part.part_name = part_table.part_name + n.to_s
		        end
		        @part.event_id = part_table.event_id
		        n = n + 1
	      	end
	    end
  	end

  	def create_meeting_time
    	self.meeting_time = Time.zone.parse(self.date.to_s + " " + self.meeting_time.strftime('%H:%M:%S'))
    end

    def create_start_time
    	self.start_time = Time.zone.parse(self.date.to_s + " " + self.start_time.strftime('%H:%M:%S'))
    end

    def create_finish_time
    	self.finish_time = Time.zone.parse(self.date.to_s + " " + self.finish_time.strftime('%H:%M:%S'))
    end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  def new
    @event = Event.new
    # cocoonでデフォルト３つ表示させるために3回作成
    3.times {@event.part_tables.build}
    # has_oneの場合のbuildはは少し表記が変わる
    @after_party = @event.build_after_party
  end

  def new_confirm
    @event = Event.new(event_params)
    render :new if @event.invalid?
    #eventモデルのcreate_partメソッドを呼び出し、パートを作成
    @event.create_part
    # チェックが入っているときに見学パートテーブル作成
    if params[:event][:observe] == '1'
      part_table = @event.part_tables.build
      part_table.part_name = "見学"
      part_table.event_id = @event.id
      part_table.observe = "見学"
    end
  end

  def create
    @event = Event.new(event_params)
    @event.create_meeting_time
    @event.create_start_time
    @event.create_finish_time
    if @event.save
      flash[:success] = "#{@event.event_name}を新たに作成しました！"
      redirect_to admin_events_path
    else
      @part = @event.parts.build
      @after_party = @event.build_after_party
      render 'new'
    end
  end

  def index
    @events= Event.all
  end

  def show
    @now = Time.current
    @event = Event.friendly.find(params[:id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @event_threads = EventThread.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @complete_musics = Music.where(event_id: @event, establishment_count:0).order(:updated_at)
    @incomplete_musics = Music.where("(event_id = ?) AND (establishment_count > ?)", @event, 0).order(:establishment_count)
  end

  def edit
    @event = Event.friendly.find(params[:id])
    @parts = Part.where(event_id: @event.id)
    @event_users = EventUser.where(event_id: @event.id)
    @entry_tables = EntryTable.joins(:part).where(part_id: @parts)
    musics = Music.where(event_id: @event.id)
    @incomplete_musics = Music.where(event_id: @event.id, establishment_status:0)
    @complete_musics = Music.where(event_id: @event.id, establishment_status:1)
  end

  def edit_confirm
    @event = Event.friendly.find(params[:event_id])
    @event.attributes = event_params
    render :edit if @event.invalid?
  end

  def update
    event = Event.friendly.find(params[:id])
    event.update(event_params)
    event.create_meeting_time
    event.create_start_time
    event.create_finish_time
    event.save(event_params)
    flash[:success] = "#{event.event_name}を更新しました！"
    redirect_to admin_event_path(event)
  end

  def destroy
    event = Event.friendly.find(params[:id])
    if event.destroy
    flash[:danger] = "#{event.event_name}を削除しました！"
    redirect_to admin_events_path
    else
      @events= Event.all
      render 'index'
    end
  end

  def timetable
    @event = Event.friendly.find(params[:event_id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @musics = Music.where(event_id: @event, establishment_count:0).order(:position)
  end

  def sort
    event = Event.friendly.find(params[:event_id])
    music = event.musics.find_by(event_id: event, establishment_count: 0, position: params[:from].to_i + 1)
    music.insert_at(params[:to].to_i + 1)
    head :ok
  end

  def timetable_releace
    event = Event.friendly.find(params[:event_id])
    if event.timetable_releace == true
      event.timetable_releace = false
    elsif event.timetable_releace == false
      event.timetable_releace = true
    end
    event.save
    redirect_back(fallback_location: admin_event_timetable_path(event.friendly_url))
  end

  private
  def event_params
    params.require(:event).permit(:after_party_id, :event_name, :friendly_url, :overview, :date,
      :meeting_time, :start_time, :finish_time, :entry_start_time, :entry_finish_time,
      :place, :place_url, :performance_fee, :visit_fee, :image, :remote_image_url,:releace_flag, :timetable_releace,
      check_val: [:observe],
      parts_attributes: [:event_id, :part_name, :_destroy, :id],
      part_tables_attributes: [:event_id, :part_name, :count, :observe, :id, :_destroy],
      after_party_attributes: [:party_place, :party_postalcode, :party_address, :party_url, :party_fee, :party_overview, :_destroy])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def confirm
    @event_user = EventUser.new
    @event = Event.friendly.find(params[:event_id])
    @part_tables = PartTable.where(event_id: @event.id).order(:id)
    @after_party = AfterParty.find_by(event_id: @event.id)
    @event_users = EventUser.where(event_id: @event.id)
  end

  def show
    @now = Time.current
  	@event = Event.friendly.find(params[:id])
  	@parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @event_threads = EventThread.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @complete_musics = Music.where(event_id: @event, establishment_count:0).order(:updated_at)
  	@incomplete_musics = Music.where("(event_id = ?) AND (establishment_count > ?)", @event, 0).order(:establishment_count)
     respond_to do |format|
      format.html
      format.csv do
        if params[:name] == "complete"
        musics_csv(@complete_musics, @parts)
        elsif params[:name] == "incomplete"
        musics_csv(@incomplete_musics, @parts)
        end
      end
    end
  end

  def musics_csv(musics, parts)
    require "csv"
    csv_data = CSV.generate(encoding: Encoding::SJIS) do |csv|

      header = %w(タイトル アーティスト名)
        parts.each do |part|
          header.push(part.part_name)
        end
      csv << header

      # body
      musics.each do |music|
        entry_tables = EntryTable.where(music_id: music.id)
        values = [
          music.title,
          music.artist
        ]
        entry_tables.each do |entry_table|
          values.push(entry_table.event_user&.user&.name)
        end
        csv << values
      end
    end
    @now = Time.current
    @event = Event.friendly.find(params[:id])
    send_data(csv_data, filename: "#{@event.friendly_id} #{@now}.csv")
  end

  def index
    now = Time.current
    @future_events = Event.where('date >= ?', now)
  	@past_events = Event.where('date < ?', now)
  end

  def timetable
    @event = Event.friendly.find(params[:event_id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @musics = Music.where(event_id: @event, establishment_count:0).order(:position)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_after_party.html.erb
<table class="table table-bordered">
  	<tbody>
        <tr>
            <th class="active"><%= f.label :party_place, "打ち上げ会場名" %></th>
            <td><%= f.text_field :party_place, size: 70, :placeholder => "打ち上げ会場名" %></td>
        </tr>
        <tr>
        	<th class="active"><%= f.label :party_postalcode, "郵便番号" %></th>
        	<td><%= f.text_field :party_postalcode, size: 7, :placeholder => "郵便番号" %></td>
        </tr>
        <tr>
        	<th class="active"><%= f.label :party_address, "住所" %></th>
        	<td><%= f.text_field :party_address, size: 70, :placeholder => "住所" %></td>
        </tr>
        <tr>
        	<th class="active"><%= f.label :party_url, "会場URL" %></th>
        	<td><%= f.text_field :party_url, size: 70, :placeholder => "会場URL" %></td>
        </tr>
        <tr>
        	<th class="active"><%= f.label :party_fee, "参加費" %></th>
        	<td><%= f.text_field :party_fee, size: 10, :placeholder => "参加費" %>円</td>
        </tr>
        <tr>
            <div class="field">
                <th class="active"><%= f.label :party_overview %></th>
                <td>
                    <%= f.hidden_field :party_overview, id: :article_text2 %>
                    <trix-editor input="article_text2"></trix-editor>
                </td>
            </div>
        </tr>
    </tbody>
</table>

app/views/admin/events/_part_table_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :part_name %>　
    パート数：<%= f.number_field :count, min:0,max:10 %>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= link_to_remove_association "削除", f %>
</div>

app/views/admin/events/edit.html.erb
<% content_for(:html_title) { "#{@event.friendly_url}編集" } %>
<div class="container">
    <div class="row"><div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="form-user style-1 rounded has-shadow-1">
                <div class="form-header">
                    <div class="form-header text-center">
                        <h2 class="form-header-title">イベント編集</h2>
                    </div>
                    <%= form_for(@event, url: admin_event_edit_confirm_path(@event.friendly_id)) do |f| %>
                    	<%= render 'layouts/error_messages', model: f.object %>
                        <table class="table table-bordered">
                          	<tbody>
	                            <tr>
		                            <th class="active"><%= f.label :event_name %></th>
		                            <td><%= f.text_field :event_name, size: 70, :placeholder => "イベント名" %></td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :friendly_url %></th>
		                        	<td><%= @event.friendly_url %></td>
		                        </tr>
		                        <tr>
	                        		<th class="active"><%= f.label :date %></th>
	                        		<td><%= f.text_field :date, size: 70, :placeholder => "日付", data: { date_format: 'YYYY-MM-DD'}, class:"datepicker" %></td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :meeting_time %></th>
		                        	<td><%= f.text_field :meeting_time, size: 70, data: { date_format: ' HH:mm'}, class:"datepicker" %>
		                        	</td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :start_time %></th>
		                        	<td><%= f.text_field :start_time, size: 70, data: { date_format: ' HH:mm'}, class:"datepicker" %>
		                        	</td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :finish_time %></th>
		                        	<td><%= f.text_field :finish_time, size: 70, data: { date_format: ' HH:mm'}, class:"datepicker" %>
		                        	</td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :entry_start_time %></th>
		                        	<td><%= f.text_field :entry_start_time, size: 70, :placeholder => "エントリー開始時間", data: { date_format: 'YYYY-MM-DD HH:mm'}, class:"datepicker" %></td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :entry_finish_time %></th>
		                        	<td><%= f.text_field :entry_finish_time, size: 70, :placeholder => "エントリー終了時間", data: { date_format: 'YYYY-MM-DD HH:mm'}, class:"datepicker" %></td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :place %></th>
		                        	<td><%= f.text_field :place, size: 70, :placeholder => "場所" %></td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :place_url %></th>
		                        	<td><%= f.text_field :place_url, size: 70, :placeholder => "参考URL" %></td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :performance_fee %></th>
		                        	<td><%= f.text_field :performance_fee, size: 10, :placeholder => "演奏参加費" %>円</td>
		                        </tr>
		                        <tr>
		                        	<th class="active"><%= f.label :visit_fee %></th>
		                        	<td><%= f.text_field :visit_fee, size: 10, :placeholder => "見学参加費" %>円</td>
		                        </tr>
		                        <tr>
	                                <th class="active"><%= f.label :image %></th>
	                                <td><%= attachment_image_tag @event, :image, id: "image_preview", fallback: "no_image.jpg", height: "300", class:"img-thumbnail" %>
	                                	<%= f.attachment_field :image, onchange: "previewFile()" %></td>
                            	</tr>
                            	<tr>
	                                <th class="active">パート</th>
		                            <td>
									    <%= f.fields_for :parts do |p| %>
										    <%= p.text_field :part_name %><br>
										    <%= p.hidden_field :id, value: p.object.id %>
									    <% end %>
									</td>
                            	</tr>
                            	<tr>
                            		<div class="field">
		                        	<th class="active"><%= f.label :overview %></th>
		                        	<td>
		                        		<%= f.hidden_field :overview, size: "20x100", id: :article_text %>
    									<trix-editor input="article_text"></trix-editor>
		                        	</td>
		                        	</div>
		                        </tr>
		                    </tbody>
		                </table>
		                <div class="form-header text-center">
                            <h2 class="form-header-title">打ち上げ</h2>
                        </div>
                        <%= f.fields_for :after_party do |ap| %>
		                	<%= render "after_party", f: ap %>
		                <% end %>

		                <div class="actions">
                          <%= f.submit '確認画面へ', class:"btn btn-lg btn-primary btn-block" %>
                        </div>
                  <% end %>
	            </div>
	        </div>
	    </div>
	</div>
</div>

app/views/admin/events/index.html.erb
<% content_for(:html_title) { "イベント一覧" } %>
<div class="container">
    <div class="row"><div class="container">
    <div class="row">
    	<div class="col-xs-12">
		<%= link_to "イベントを作成する", new_admin_event_path, class: "btn btn-lg btn-primary btn-block" %><br>
		</div>
		<% @events.each do |event| %>
			<div class="col-xs-3 text-center">
				<div class="event_container round_border">
					<%= link_to event_path(event.friendly_url) do %>
							<%= link_to admin_event_path(event.friendly_url) do %>
								<%= attachment_image_tag event, :image, :fill, 200, 200, format: 'jpeg', fallback: "no_image.jpg", size:'200x200', class:"img-thumbnail" %>
								<h4><%= event.event_name %>(<%= event.event_users.count %>名)</h4>
							<% end %>
							<%= event.date %> <%= event.meeting_time.to_s(:time) %>〜<%= event.finish_time.to_s(:time) %><br>
							<%= link_to "編集する", edit_admin_event_path(event.friendly_url), class:"btn btn-xs btn-warning"%>
							<%= link_to "削除する", admin_event_path(event.friendly_url), method: :delete , class:"btn btn-xs btn-danger", data: {confirm: "本当に削除してもよろしいですか？"} %>
							<%= link_to "TT作成", admin_event_timetable_path(event.friendly_url), class:"btn btn-xs btn-success"%>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/events/show.html.erb
<% content_for(:html_title) { "#{@event.friendly_url}" } %>
<div class="container">
    <div class="row">
		<div class="col-xs-12 clearfix">
			<div class="event-header">
				<h2><%= link_to "#{@event.event_name}", admin_event_path(@event) %>
					<p class="pull-right">管理者</p>
				</h2>
				<%= @event.date.to_s(:date) %> (<%= @event.start_time.to_s(:time) %>〜<%= @event.finish_time.to_s(:time) %>)
				<br><br>
			</div>
		</div>
		<div class="event-container clearfix">
			<div class="col-xs-3">
				<div class="text-center">
				<%= attachment_image_tag @event, :image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:'300x300', class:"img-thumbnail" %>
				</div>
			</div>
			<div class="col-xs-9">
				<table class="table table-bordered">
					<tbody>
					    <tr>
					        <th class="active text-right">会場</th>
					        <td><%= link_to "#{@event.place}", @event.place_url %></td>
					    </tr>
					    <tr>
					        <th class="active text-right">集合時間</th>
					        <td><%= @event.meeting_time.to_s(:time) %></td>
					    </tr>
					    <tr>
					        <th class="active text-right">演奏時間</th>
					        <td><%= @event.start_time.to_s(:time) %>〜<%= @event.finish_time.to_s(:time) %></td>
					    </tr>
					    <tr>
					        <th class="active text-right">参加費</th>
					        <td>演奏参加：<%= @event.performance_fee %>円　見学参加：<%= @event.visit_fee %>円</td>
					    </tr>
					    <tr>
					        <th class="active text-right">打ち上げ会場</th>
					        <td><%= link_to "#{@event.after_party.party_place}", @event.after_party.party_url %></td>
					    </tr>
					</tbody>
				</table>
				<div class="text-right">
					<%= link_to admin_event_timetable_path(@event.friendly_url), class:"btn btn-lg btn-success" do %>
						<i class="fas fa-list"></i> タイムテーブル作成 
					<% end %>
					<%= link_to event_party_path(@event.friendly_url), class:"btn btn-lg btn-warning" do %>
						<i class="fas fa-beer icon_custom,"></i> 打ち上げ詳細 
					<% end %>
					<%= link_to event_event_users_path(@event.friendly_url), class:"btn btn-lg btn-info" do %>
						<i class="fas fa-users"></i> 参加者一覧
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-xs-12">
		 	<div class="panel panel-default">
		    	<div class="panel-heading">イベント概要</div>
		    	<div class="panel-body">
		    		<%= sanitize @event.overview, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img table tr td em br strong div), attributes:  %w(id class href) %>
				</div>
			</div>
		</div>

		<div class="col-xs-12 clearfix">
			<h3>楽曲一覧　<span style="font-size:15px;" >エントリー期間:　<%= @event.entry_start_time %> 〜 <%= @event.entry_finish_time %></span></h3>
			<h4>成立曲 (<%= @complete_musics.count %>曲)</h4>
				<%= render 'admin/entry_tables/adminentrytable', parts: @parts, event: @event, entry_tables: @entry_tables, event_users: @event_users, musics: @complete_musics, now: @now %>
			<h4>未成立曲 (<%= @incomplete_musics.count %>曲)</h4>
			<%= render 'admin/entry_tables/adminentrytable', parts: @parts, event: @event, entry_tables: @entry_tables, event_users: @event_users, musics: @incomplete_musics, now: @now %>
		</div>
	</div>
</div>

app/views/admin/events/timetable.html.erb
<% content_for(:html_title) { "#{@event.event_name}タイムテーブル作成" } %>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="container">
    <div class="row">
    	<div class="col-xs-12 clearfix">
			<div class="event-header">
				<h2><%= link_to "#{@event.event_name}", admin_event_path(@event) %>
					<p class="pull-right">管理者</p>
				</h2>
				<%= @event.date.to_s(:date) %> (<%= @event.start_time.to_s(:time) %>〜<%= @event.finish_time.to_s(:time) %>)
				<br><br>
			</div>
		</div>
    	<div class="form-header text-center">
            <h2 class="form-header-title">
            	<%= @event.event_name %>タイムテーブル</h2>
        </div>
        <div class="clearfix">
	        <div class="col-xs-1">
		        <div class="table-responsive">
		        	<table class="table">
		        		<thead>
							<tr>
								<td>　</td>
							</tr>
						</thead>
						<tbody>
							<% @musics.count.times do |n| %>
							<tr>
								<td class="pull-right" style="border-top: 1px solid #ddd0;">
									<%= (@event.start_time + 600 * n).to_s(:time) %>
								</td>
							</tr>
							<% end %>
						</tbody>
		        	</table>
		        </div>
		    </div>
		    <div class="col-xs-11">
				<div class="table-responsive">
					<table class="table table-bordered" style="table-layout:fixed; white-space: nowrap;">
						<thead>
							<tr class="info">
								<th class="active" style="width:100px;">曲名</th>
								<th class="active" style="width:100px;">アーティスト名</th>
								<% @parts.each do |part| %>
									<th class="active" style="width:80px;"><%= part.part_name %></th>
								<% end %>
							</tr>
						</thead>
						<tbody id="sortable">
							<% @musics.each do |music| %>
							<tr>
								<th>
									<div>
									<%= link_to "#{music.title}", event_music_path(@event.friendly_url, music.id) %>
									</div>
								</th>
								<td>
									<%= music.artist %>
								</td>
								<% @parts.each do |part| %>
									<!-- パートが不要な時 -->
									<% if @entry_tables.find_by(music_id: music, part_id: part)&.requirement_status == "不要" %>
									<td>　</td>
									<!-- エントリーステータスが必須または任意の時 -->
									<% else %>
										<!-- 楽曲にユーザーがエントリーしていない時 -->
										<% if @entry_tables.find_by(music_id: music, part_id: part)&.event_user_id == nil %>
											<td>　</td>
										<!-- 楽曲にユーザーがエントリーしている時 -->
										<% else %>
											<td>
											<%= link_to "#{@entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name}", user_path(@entry_tables.find_by(music_id: music, part_id: part).event_user.user) %>
											</td>
										<% end %>
									<% end %>
								<% end %>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<%= hidden_field_tag :event_id, @event.id %>
		<% if @event.timetable_releace == false %>
			<%= link_to "タイムテーブル公開", admin_event_timetable_releace_path(@event.friendly_url), method: :patch, class:"btn btn-lg btn-block btn-primary" %>
		<% elsif @event.timetable_releace == true %>
			<%= link_to "タイムテーブル非公開", admin_event_timetable_releace_path(@event.friendly_url), method: :patch, class:"btn btn-lg btn-block btn-danger" %>
		<% end %>
	</div>
</div>