config/routes.rb
Rails.application.routes.draw do
	devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
	devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
    }

    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    post '/callback' => 'linebot#callback'
    get 'users/twitter_new' => 'users#twitter_new', as: 'user_twitter_new'
    patch 'users/twitter_update/:id' => 'users#twitter_update', as: 'user_twitter_update'
    resources :users, only: [:show, :edit, :update]
    resources :events, only: [:show, :index] do
        get '/timetable' => 'events#timetable', as: 'timetable'
        get '/confirm' => 'events#confirm', as: 'confirm'
        get '/afterparty' => 'after_parties#show', as: 'party'
        resources :event_users, only: [:index, :create, :update, :destroy]
        resources :entry_tables, only: [:update, :destroy]
        post 'musics/new_confirm' => 'musics#new_confirm', as: 'music_new_confirm'
        patch 'musics/:id/edit_confirm' => 'musics#edit_confirm', as: 'music_edit_confirm'
        resources :musics, except: [:index] do
            resources :music_comments, only: [:create, :destroy]
            post '/lyrics/new_confirm' => 'lyrics#new_confirm', as: 'lyric_new_confirm'
            patch '/lyrics/:id/edit_confirm' => 'lyrics#edit_confirm', as: 'lyric_edit_confirm'
            patch '/lyrics/select_confirm' => 'lyrics#select_confirm', as: 'lyric_select_confirm'
            patch '/lyrics/select' => 'lyrics#select', as: 'lyric_select'
            resources :lyrics, only: [:new, :create, :edit, :update, :destroy]
        end
        post 'event_threads/confirm' => 'event_threads#confirm', as: 'threads_confirm'
        resources :event_threads, only: [:new, :create, :show, :update, :destroy] do
            resources :event_thread_comments, only: [:create, :destroy]
        end
    end

    namespace :admin do
      root 'homes#top'
    end

    namespace :admin do
      post 'events/new_confirm' => 'events#new_confirm', as: 'new_confirm'
      resources :events do
        get '/timetable' => 'events#timetable', as: 'timetable'
        patch '/timetable/releace' => 'events#timetable_releace', as: 'timetable_releace'
        patch '/timetable/sort' => 'events#sort'
        patch 'edit_confirm' => 'events#edit_confirm', as: 'edit_confirm'
        resources :entry_tables, only: [:update]
        resources :event_users, only: [:index, :update, :destroy]
      end
    end

    namespace :admin do
      resources :users, only: [:index, :show, :edit, :update]
    end
end

app/models/event_thread.rb
class EventThread < ApplicationRecord
	has_many :event_thread_comments, dependent: :destroy
	belongs_to :event
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/event_threads_controller.rb
class EventThreadsController < ApplicationController
before_action :show_header, only: [:new, :confirm, :show, :edit]
  def show_header
    @event = Event.friendly.find(params[:event_id])
    @event_users = EventUser.where(event_id: @event)
  end

  def new
  	@event_thread = EventThread.new(params[:id])
  	@event_threads = EventThread.where(event_id: @event)
  end

  def show
    @event_thread = EventThread.find(params[:id])
    @event_threads = EventThread.where(event_id: @event)
    @event_thread_comments = EventThreadComment.where(event_thread_id: @event_thread)
    @event_users = EventUser.where(event_id: @event)
    if EventUser.find_by(event_id: @event, user_id: current_user).presence
      @event_thread_comment = EventThreadComment.new
    end
  end

  def confirm
    @event_thread = EventThread.new(event_thread_params)
    render :new if @event_thread.invalid?
  end

  def create
  	@event = Event.friendly.find(params[:event_id])
    @event_thread = current_user.event_threads.new(event_thread_params)
	  @event_thread.event_id = @event.id
	 if @event_thread.save
      calculate_level(10)
	    flash[:success] = "「#{@event_thread.title}」を作成しました！"
	    redirect_to event_event_thread_path(@event.friendly_id, @event_thread)
	 else
	    render :new
	 end
  end

  def destroy
  	@event_thread = EventThread.find(params[:id])
  	@event_thread.destroy
    calculate_level(-10)
    flash[:danger] = "「#{@event_thread.title}」を削除しました！"
  	redirect_to event_path(@event_thread.event.friendly_id)
  end

  def calculate_level(exp)
    if exp < 0
      current_user.level_up?(exp)
      flash[:info] = "掲示板の削除 #{exp.to_i}pt"
    elsif current_user.level_up?(exp)
      flash[:info] = "掲示板作成 #{exp.to_i}pt Get! Level UP!"
    else
      flash[:info] = "掲示板作成 #{exp.to_i}pt Get!"
    end
  end

  private
  def event_thread_params
  	params.require(:event_thread).permit(:event_id, :user_id, :title, :body)
  end
end

app/helpers/event_threads_helper.rb
module EventThreadsHelper
end

app/views/event_threads/_thread_index.html.erb
<div class="col-xs-12 clearfix">
 	<div class="panel panel-info">
    	<div class="panel-heading">
    		<h3 class="panel-title">掲示板</h3>
    	</div>
    	<div class="panel-body">
			<% event_threads.each do |event_thread| %>
				<div class="col-xs-6">
					<%= link_to event_event_thread_path(event.friendly_id, event_thread.id) do %>
					<i class="fas fa-greater-than"></i> 
					<%= event_thread.title %> (<%= event_thread.event_thread_comments.count %>)
					<% end %>
				</div>
			<% end %>
			<% if user_signed_in? %>
				<span><%= link_to new_event_event_thread_path(event), class:"btn btn-lg btn-primary pull-right" do %>
					<i class="fas fa-plus-circle icon_custom"></i> 新規作成
					<% end %>
				</span>
			<% end %>
		</div>
	</div>
</div>

app/views/event_threads/confirm.html.erb
<% content_for(:html_title) { "新規掲示板作成" } %>
<div class="container">
    <div class="row">
    	<div class="clearfix">
        <%= render 'events/event-header', event: @event, event_users: @event_users %>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-user style-1 rounded has-shadow-1">
                <div class="form-header">
                    <div class="form-header text-center">
                        <h2 class="form-header-title">新規掲示板作成</h2>
                    </div>
                    <%= form_for [@event, @event_thread], url: event_event_threads_path(@event.friendly_id) do |f| %>
                    <%= render 'layouts/error_messages', model: f.object %>
                    <table class="table table-bordered">
                      	<tbody>
                            <tr>
	                            <th class="active"><%= f.label :title %></th>
	                            <td><%= @event_thread.title %></td>
	                            <%= f.hidden_field :title %>
	                        </tr>
	                        <div class="field">
	                        	<th class="active"><%= f.label :body %></th>
	                        	<td><%= sanitize @event_thread.body, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img table tr td em br strong div), attributes:  %w(id class href) %>
                                </td>
	                        	<%= f.hidden_field :body %>
	                        </div>
	                    </tbody>
	                </table>
	                <div class="actions">
                      <%= f.submit '掲示板を作成する', class:"btn btn-primary btn-block" %><br>
                    </div>
                  <% end %>
	            </div>
	        </div>
	    </div>
	</div>
</div>

app/views/event_threads/new.html.erb
<% content_for(:html_title) { "新規掲示板作成" } %>
<div class="container">
    <div class="row">
    	<div class="clearfix">
        <%= render 'events/event-header', event: @event, event_users: @event_users %>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-user style-1 rounded has-shadow-1">
                <div class="form-header">
                    <div class="form-header text-center">
                        <h2 class="form-header-title">新規掲示板作成</h2>
                    </div>
                    <%= form_for [@event, @event_thread], url: event_threads_confirm_path(@event.friendly_id) do |f| %>
                    <%= render 'layouts/error_messages', model: f.object %>
                    <table class="table table-bordered">
                      	<tbody>
                            <tr>
	                            <th class="active"><%= f.label :title %></th>
	                            <td><%= f.text_field :title,:placeholder => "タイトル" %></td>
	                        </tr>
	                        <div class="field">
	                        	<th class="active"><%= f.label :body %></th>
	                        	<td>
	                        		<%= f.hidden_field :body, size: "20x100", id: :article_text %>
									<trix-editor input="article_text"></trix-editor>
	                        	</td>
	                        </div>
	                    </tbody>
	                </table>
	                <div class="actions">
	                	<%= f.hidden_field :user_id, :value => current_user.id %>
	                	<%= f.hidden_field :event_id, :value => @event.id %>
                      <%= f.submit '確認画面', class:"btn btn-primary btn-block" %>
                    <br>
                    </div>
                  <% end %>
	            </div>
	        </div>
	    </div>
	</div>
</div>

app/views/event_threads/show.html.erb
<% content_for(:html_title) { "#{@event_thread.title}" } %>
<div class="container">
    <div class="row">
        <div class="clearfix">
        <%= render 'events/event-header', event: @event, event_users: @event_users %>
        <br>
        <%= render 'event_threads/thread_index', event: @event, event_threads: @event_threads %>
        </div>

        <div class="col-xs-12 clearfix">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><%= @event_thread.title %>
                        <span>
                            <% if @event_thread.user == current_user %>
                                  <%= link_to "削除", event_event_thread_path(@event,@event_thread), method: :delete, class: " pull-right", data: {confirm: "この掲示板を本当に削除してもよろしいですか？"} %>
                            <% end %>
                        </span>
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="voice-img" >
                        <%= attachment_image_tag @event_thread.user, :image, format: 'jpeg', fallback: "no_image.jpg", size:'60x60', class:"img-circle" %><br>
                        <div class="voice-img-description">
                            <%= link_to "#{@event_thread.user.name}", user_path(@event_thread.user_id) %>
                        </div>
                    </div>
                    <div class="voice">
                        <div class="voice-text">
                            <%=safe_join(@event_thread.body.split("\n"),tag(:br))%><br>
                        </div>
                        <div class="comment-datetime">
                            <%= @event_thread.created_at.to_s(:datetime) %>
                        </div>
                    </div><br>
                    <% @event_thread_comments.each do |event_thread_comment| %>
                        <div class="voice-img" >
                            <%= attachment_image_tag event_thread_comment.user, :image, format: 'jpeg', fallback: "no_image.jpg", size:'60x60', class:"img-circle" %><br>
                            <div class="voice-img-description">
                                <%= link_to "#{event_thread_comment.user.name}", user_path(event_thread_comment.user_id) %>
                            </div>
                        </div>
                        <div class="voice">
                            <div class="voice-text">
                                <%= safe_join(event_thread_comment.comment.split("\n"),tag(:br))%>
                            </div>
                            <div class="comment-datetime">
                                <% if event_thread_comment.user == current_user %>
                                    <%= link_to "削除", event_event_thread_event_thread_comment_path(@event,@event_thread,event_thread_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
                                <% end %>
                                <%= event_thread_comment.created_at.to_s(:datetime) %>
                            </div>
                        </div><br>
                        <span class="comment-score"><% event_thread_comment&.score %></span>
                    <% end %>
                    <% if user_signed_in? && @event_users.where(user_id: current_user.id).presence %>
                        <%= form_for [@event, @event_thread, @event_thread_comment] do |f| %>
                            <%= render 'layouts/error_messages', model: f.object %>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <%= f.text_area :comment, rows:'5', class: "form-control", placeholder: "コメントをここに" %>
                                    </div>
                                </div>
                            <%= f.submit "送信する", class: "btn btn-lg btn-primary pull-right" %>
                        <% end %>
                    <% end %>
                </div>
        	</div>
        </div>
    </div>
</div>