config/routes.rb
Rails.application.routes.draw do
	devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
	devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
    }

    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    post '/callback' => 'linebot#callback'
    get 'users/twitter_new' => 'users#twitter_new', as: 'user_twitter_new'
    patch 'users/twitter_update/:id' => 'users#twitter_update', as: 'user_twitter_update'
    resources :users, only: [:show, :edit, :update]
    resources :events, only: [:show, :index] do
        get '/timetable' => 'events#timetable', as: 'timetable'
        get '/confirm' => 'events#confirm', as: 'confirm'
        get '/afterparty' => 'after_parties#show', as: 'party'
        resources :event_users, only: [:index, :create, :update, :destroy]
        resources :entry_tables, only: [:update, :destroy]
        post 'musics/new_confirm' => 'musics#new_confirm', as: 'music_new_confirm'
        patch 'musics/:id/edit_confirm' => 'musics#edit_confirm', as: 'music_edit_confirm'
        resources :musics, except: [:index] do
            resources :music_comments, only: [:create, :destroy]
            post '/lyrics/new_confirm' => 'lyrics#new_confirm', as: 'lyric_new_confirm'
            patch '/lyrics/:id/edit_confirm' => 'lyrics#edit_confirm', as: 'lyric_edit_confirm'
            patch '/lyrics/select_confirm' => 'lyrics#select_confirm', as: 'lyric_select_confirm'
            patch '/lyrics/select' => 'lyrics#select', as: 'lyric_select'
            resources :lyrics, only: [:new, :create, :edit, :update, :destroy]
        end
        post 'event_threads/confirm' => 'event_threads#confirm', as: 'threads_confirm'
        resources :event_threads, only: [:new, :create, :show, :update, :destroy] do
            resources :event_thread_comments, only: [:create, :destroy]
        end
    end

    namespace :admin do
      root 'homes#top'
    end

    namespace :admin do
      post 'events/new_confirm' => 'events#new_confirm', as: 'new_confirm'
      resources :events do
        get '/timetable' => 'events#timetable', as: 'timetable'
        patch '/timetable/releace' => 'events#timetable_releace', as: 'timetable_releace'
        patch '/timetable/sort' => 'events#sort'
        patch 'edit_confirm' => 'events#edit_confirm', as: 'edit_confirm'
        resources :entry_tables, only: [:update]
        resources :event_users, only: [:index, :update, :destroy]
      end
    end

    namespace :admin do
      resources :users, only: [:index, :show, :edit, :update]
    end
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :musics, -> { order(position: :asc) }, dependent: :destroy
	has_many :event_users, dependent: :destroy
	has_many :parts, dependent: :destroy
	has_many :part_tables, dependent: :destroy
	has_one :after_party, dependent: :destroy
	attachment :image

	accepts_nested_attributes_for :part_tables, allow_destroy: true, update_only: true
	accepts_nested_attributes_for :parts, allow_destroy: true, update_only: true
	accepts_nested_attributes_for :after_party, allow_destroy: true, update_only: true

    validates :event_name, presence: true, uniqueness: true
	validates :friendly_url, length: { in: 3..20 },
                         uniqueness: true,
                         format: { with: /\A[\w@-]*[A-Za-z][\w@-]*\z/ }
	validates :date, presence: true
	validates :meeting_time, presence: true
	validates :start_time, presence: true
	validates :finish_time, presence: true
	validates :place, presence: true
	validates :performance_fee, presence: true
	validates :visit_fee, presence: true


	include FriendlyId
  		friendly_id :friendly_url

  	def create_part
  		self.part_tables.each do |part_table|
	      	m = part_table.count
	      	n = 1
	      	m.times do
		        @part = self.parts.build
		        if m == 1
		          	@part.part_name = part_table.part_name
		        elsif m > 1
		          	@part.part_name = part_table.part_name + n.to_s
		        end
		        @part.event_id = part_table.event_id
		        n = n + 1
	      	end
	    end
  	end

  	def create_meeting_time
    	self.meeting_time = Time.zone.parse(self.date.to_s + " " + self.meeting_time.strftime('%H:%M:%S'))
    end

    def create_start_time
    	self.start_time = Time.zone.parse(self.date.to_s + " " + self.start_time.strftime('%H:%M:%S'))
    end

    def create_finish_time
    	self.finish_time = Time.zone.parse(self.date.to_s + " " + self.finish_time.strftime('%H:%M:%S'))
    end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  def new
    @event = Event.new
    # cocoonでデフォルト３つ表示させるために3回作成
    3.times {@event.part_tables.build}
    # has_oneの場合のbuildはは少し表記が変わる
    @after_party = @event.build_after_party
  end

  def new_confirm
    @event = Event.new(event_params)
    render :new if @event.invalid?
    #eventモデルのcreate_partメソッドを呼び出し、パートを作成
    @event.create_part
    # チェックが入っているときに見学パートテーブル作成
    if params[:event][:observe] == '1'
      part_table = @event.part_tables.build
      part_table.part_name = "見学"
      part_table.event_id = @event.id
      part_table.observe = "見学"
    end
  end

  def create
    @event = Event.new(event_params)
    @event.create_meeting_time
    @event.create_start_time
    @event.create_finish_time
    if @event.save
      flash[:success] = "#{@event.event_name}を新たに作成しました！"
      redirect_to admin_events_path
    else
      @part = @event.parts.build
      @after_party = @event.build_after_party
      render 'new'
    end
  end

  def index
    @events= Event.all
  end

  def show
    @now = Time.current
    @event = Event.friendly.find(params[:id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @event_threads = EventThread.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @complete_musics = Music.where(event_id: @event, establishment_count:0).order(:updated_at)
    @incomplete_musics = Music.where("(event_id = ?) AND (establishment_count > ?)", @event, 0).order(:establishment_count)
  end

  def edit
    @event = Event.friendly.find(params[:id])
    @parts = Part.where(event_id: @event.id)
    @event_users = EventUser.where(event_id: @event.id)
    @entry_tables = EntryTable.joins(:part).where(part_id: @parts)
    musics = Music.where(event_id: @event.id)
    @incomplete_musics = Music.where(event_id: @event.id, establishment_status:0)
    @complete_musics = Music.where(event_id: @event.id, establishment_status:1)
  end

  def edit_confirm
    @event = Event.friendly.find(params[:event_id])
    @event.attributes = event_params
    render :edit if @event.invalid?
  end

  def update
    event = Event.friendly.find(params[:id])
    event.update(event_params)
    event.create_meeting_time
    event.create_start_time
    event.create_finish_time
    event.save(event_params)
    flash[:success] = "#{event.event_name}を更新しました！"
    redirect_to admin_event_path(event)
  end

  def destroy
    event = Event.friendly.find(params[:id])
    if event.destroy
    flash[:danger] = "#{event.event_name}を削除しました！"
    redirect_to admin_events_path
    else
      @events= Event.all
      render 'index'
    end
  end

  def timetable
    @event = Event.friendly.find(params[:event_id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @musics = Music.where(event_id: @event, establishment_count:0).order(:position)
  end

  def sort
    event = Event.friendly.find(params[:event_id])
    music = event.musics.find_by(event_id: event, establishment_count: 0, position: params[:from].to_i + 1)
    music.insert_at(params[:to].to_i + 1)
    head :ok
  end

  def timetable_releace
    event = Event.friendly.find(params[:event_id])
    if event.timetable_releace == true
      event.timetable_releace = false
    elsif event.timetable_releace == false
      event.timetable_releace = true
    end
    event.save
    redirect_back(fallback_location: admin_event_timetable_path(event.friendly_url))
  end

  private
  def event_params
    params.require(:event).permit(:after_party_id, :event_name, :friendly_url, :overview, :date,
      :meeting_time, :start_time, :finish_time, :entry_start_time, :entry_finish_time,
      :place, :place_url, :performance_fee, :visit_fee, :image, :remote_image_url,:releace_flag, :timetable_releace,
      check_val: [:observe],
      parts_attributes: [:event_id, :part_name, :_destroy, :id],
      part_tables_attributes: [:event_id, :part_name, :count, :observe, :id, :_destroy],
      after_party_attributes: [:party_place, :party_postalcode, :party_address, :party_url, :party_fee, :party_overview, :_destroy])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def confirm
    @event_user = EventUser.new
    @event = Event.friendly.find(params[:event_id])
    @part_tables = PartTable.where(event_id: @event.id).order(:id)
    @after_party = AfterParty.find_by(event_id: @event.id)
    @event_users = EventUser.where(event_id: @event.id)
  end

  def show
    @now = Time.current
  	@event = Event.friendly.find(params[:id])
  	@parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @event_threads = EventThread.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @complete_musics = Music.where(event_id: @event, establishment_count:0).order(:updated_at)
  	@incomplete_musics = Music.where("(event_id = ?) AND (establishment_count > ?)", @event, 0).order(:establishment_count)
     respond_to do |format|
      format.html
      format.csv do
        if params[:name] == "complete"
        musics_csv(@complete_musics, @parts)
        elsif params[:name] == "incomplete"
        musics_csv(@incomplete_musics, @parts)
        end
      end
    end
  end

  def musics_csv(musics, parts)
    require "csv"
    csv_data = CSV.generate(encoding: Encoding::SJIS) do |csv|

      header = %w(タイトル アーティスト名)
        parts.each do |part|
          header.push(part.part_name)
        end
      csv << header

      # body
      musics.each do |music|
        entry_tables = EntryTable.where(music_id: music.id)
        values = [
          music.title,
          music.artist
        ]
        entry_tables.each do |entry_table|
          values.push(entry_table.event_user&.user&.name)
        end
        csv << values
      end
    end
    @now = Time.current
    @event = Event.friendly.find(params[:id])
    send_data(csv_data, filename: "#{@event.friendly_id} #{@now}.csv")
  end

  def index
    now = Time.current
    @future_events = Event.where('date >= ?', now)
  	@past_events = Event.where('date < ?', now)
  end

  def timetable
    @event = Event.friendly.find(params[:event_id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @event_users = EventUser.where(event_id: @event.id)
    @entry_tables = EntryTable.where(part_id: @parts)
    @musics = Music.where(event_id: @event, establishment_count:0).order(:position)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event-header.html.erb
<div class="clearfix">
	<div class="col-xs-12">
		<div class="event-header">
			<h2><%= link_to "#{event.event_name}", event_path(event) %>
					<% if user_signed_in? %>
					    <% if event.finish_time < Time.current %>
					    	<p class="pull-right">終了</p>
					    <% elsif event_users.where(user_id: current_user.id).empty? %>
						<%= link_to "参加する！", event_confirm_path(event.friendly_url), class: "btn btn-lg btn-primary pull-right"%>
						<% else %>
							<p class="pull-right">参加中</p>
						<% end %>
					<% else %>
						<div class="btn btn-lg btn-primary pull-right">
							<a class="link" data-toggle="modal" data-target="#loginModal" style="color:white;">参加する！</a>
						</div>
					<% end %>
				</h2>
			<%= event.date.to_s(:date) %> (<%= event.start_time.to_s(:time) %>〜<%= event.finish_time.to_s(:time) %>)
			<br><br>
		</div>
	</div>
</div>
<%= render 'homes/modal_signin' %>

app/views/events/_event.html.erb
<%= link_to event_path(event.friendly_url) do %>
	<div class="event-card">
		<div class="top-content">
			<%= image_tag('LLBS_image'+event.date.strftime("%m")+'.jpg', class:"event-image") %>
			<div class="date-container">
				<div class="event-status">
					<span>参加募集中</span>
				</div>
				<div class="date-status">
					<span class="month"><%= event.date.strftime("%-m月") %></span>
					<span class="date"><%= event.date.strftime("%e") %></span>
				</div>
			</div>
		</div>
		<div class="bottom-content">
			<div class="event-status">
				<span>参加募集中</span>
			</div>
			<div class="event-title"><%= event.event_name %></div>
			<div class="event-desc">
				<span class="event-desc__time"><%= event.meeting_time.to_s(:time) %>〜</span>
				<span class="event-desc__place"><%= event.place %></span>
			</div>
		</div>
	</div>
<% end %>

app/views/events/_modal_attendance.html.erb
<div class="modal fade" id="attendanceModal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
				<h4 class="modal-title">エントリー</h4>
			</div>
			<div class="modal-body">
				エントリーにはイベント参加が必要です。
			</div>
			<div class="modal-footer">
				<%= link_to "参加する！", event_confirm_path(event.friendly_url), data: {"turbolinks" => false} , class: "btn btn-primary pull-right"%>
				<button type="button" class="btn btn-default pull-left" data-dismiss="modal">閉じる</button>
			</div>
		</div>
	</div>
</div>

app/views/events/confirm.html.erb
<% content_for(:html_title) { "#{@event.event_name}参加確認" } %>
<div class="container">
    <div class="row">
    	<%= render 'events/event-header', event: @event, event_users: @event_users %>
		<h2><%= @event.event_name %>参加確認画面</h2>
		<%= form_with(model: @event_user, local: true, url: event_event_users_path ) do |f| %>
				<%= render 'layouts/error_messages', model: f.object %>
			<br>
			参加にあたってのご注意にご同意いただき、パートを選択してください。<br>
			<br>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h4 class="panel-title">注意事項</h4>
				</div>
				<div class="panel-body">
					<h4>イベント参加に関する注意</h4>
					・開催日近くのキャンセルは他の参加者に迷惑がかかります。確実に予定を押さえた上で登録しましょう。<br>
					・キャンセルされた場合、スタジオ代の請求、今後の参加制限などの可能性がありますのでご了承ください。<br>
					・選択したパートと異なるパートへのエントリーを主目的とした参加登録は原則お控えください。<br>
					<br>
				</div>
			</div>
				<%= f.hidden_field :user_id, value: current_user.id %>
				<%= f.hidden_field :event_id, value: @event.id %>
				<h4>参加パート：<%= f.select :part_table_id, @part_tables.map { |part_table| [part_table.part_name, part_table.id] }, {include_blank: '選択してください'} %></h4><br>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h4 class="panel-title"><%= @event.event_name %>打ち上げについて</h4>
				</div>
				<div class="panel-body">
					<%= render 'after_parties/after_party', event: @event, event_users: @event_users, after_party: @after_party, event_current_user: @event_current_user%>
				</div>
			</div>
			<h4>打ち上げ出席予定：<%= f.select :party_participate, ["参加", "検討中", "不参加"], {include_blank: '選択してください'} %></h4>

			<%= f.submit "上記の内容で#{@event.event_name}に参加する！", class:"btn btn-lg btn-danger btn-block" %>
		<% end %>
	</div>
</div>

app/views/events/index.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'events', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<% content_for(:html_title) { "イベント一覧" } %>
<div class="container">
    <div class="row">
    	<ul class="nav nav-tabs">
			<li class="active col-xs-6"><a href="#sampleContentA" data-toggle="tab">開催予定のイベント</a></li>
			<li class="col-xs-6"><a href="#sampleContentB" data-toggle="tab">終了したイベント</a></li>
		</ul>
		<!-- タブ内容 -->
		<div class="tab-content">
			<div class="tab-pane fade in active" id="sampleContentA">
				<div class="container">
					<% if @future_events.blank? %>
						<h2 class="events-head">イベントはありません</h2>
					<% else %>
						<h2 class="events-head">イベント一覧</h2>
						<div class="event-wrapper">
							<%= render partial: 'events/event', collection: @future_events %>
						</div>
					<% end %>
				</div>
			</div>
			<div class="tab-pane fade in" id="sampleContentB">
				<h2 class="events-head">イベント一覧</h2>
				<div class="event-wrapper">
					<%= render partial: 'events/event', collection: @past_events %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<% content_for(:html_title) { "#{@event.event_name}" } %>
<div class="container">
    <div class="row">
    	<%= render 'events/event-header', event: @event, event_users: @event_users %>
		<div class="event-container clearfix">
			<div class="col-xs-3">
				<div class="text-center">
				<%= attachment_image_tag @event, :image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:'300x300', class:"img-thumbnail" %>
				</div>
			</div>
			<div class="col-xs-9">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th class="active text-right info">会場</th>
							<td><%= link_to "#{@event.place}", @event.place_url %></td>
						</tr>
						<tr>
							<th class="active text-right info">集合時間</th>
							<td><%= @event.meeting_time.to_s(:time) %></td>
						</tr>
						<tr>
							<th class="active text-right info">演奏時間</th>
							<td><%= @event.start_time.to_s(:time) %>〜<%= @event.finish_time.to_s(:time) %></td>
						</tr>
						<tr>
							<th class="active text-right info">参加費</th>
							<td>演奏参加：<%= @event.performance_fee %>円　見学参加：<%= @event.visit_fee %>円</td>
						</tr>
						<tr>
							<th class="active text-right info">打ち上げ会場</th>
							<td><%= link_to "#{@event.after_party.party_place}", @event.after_party.party_url %></td>
						</tr>
					</tbody>
				</table>
				<div class="text-right">
					<% if @event.timetable_releace == true %>
						<%= link_to event_timetable_path(@event.friendly_url), class:"btn btn-lg btn-success" do %>
							<i class="fas fa-list"></i> タイムテーブル 
						<% end %>
					<% end %>
					<%= link_to event_party_path(@event.friendly_url), class:"btn btn-lg btn-warning" do %>
						<i class="fas fa-beer icon_custom,"></i> 打ち上げ詳細 
					<% end %>
					<%= link_to event_event_users_path(@event.friendly_url), class:"btn btn-lg btn-info" do %>
						<i class="fas fa-users"></i> 参加者一覧
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-xs-12">
		 	<div class="panel panel-default panel-info">
		    	<div class="panel-heading">イベント概要</div>
		    	<div class="panel-body">
		    		<%= sanitize @event.overview, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img table tr td em br strong div), attributes:  %w(id class href) %>
				</div>
			</div>
		</div>

		<%= render 'event_threads/thread_index', event: @event, event_threads: @event_threads %>

		<div class="col-xs-12 clearfix">
			<h3>楽曲一覧　<span style="font-size:15px;" >エントリー期間:　<%= @event.entry_start_time %> 〜 <%= @event.entry_finish_time %></h3>
			<h4>成立曲 (<%= @complete_musics.count %>曲)
				<span style="font-size: 15px;">
					<%= link_to ">>CSV出力", event_path(@event, format: :csv, name: "complete"), class: "pull-right" %>
				</span>
			</h4>
			<%= render 'entry_tables/entrytable', parts: @parts, event: @event, entry_tables: @entry_tables, event_users: @event_users, musics: @complete_musics, now: @now %>

			<h4>未成立曲 (<%= @incomplete_musics.count %>曲)
				<span style="font-size: 15px;">
					<%= link_to ">>CSV出力", event_path(@event, format: :csv, name: "incomplete"), class: "pull-right" %>
				</span>
			</h4>
			<%= render 'entry_tables/entrytable', parts: @parts, event: @event, entry_tables: @entry_tables, event_users: @event_users, musics: @incomplete_musics, now: @now %>

			<% if user_signed_in? && @event_users.where(user_id: current_user.id).presence && @event.finish_time > @now %>
				<%= link_to new_event_music_path(@event.friendly_id), class: "btn btn-lg btn-primary btn-block" do %>
				<i class="fas fa-plus-circle icon_custom"></i> 曲を追加する
				<% end %>
			<% end %>
		<br>
		</div>
	</div>
</div>

app/views/events/timetable.html.erb
<% content_for(:html_title) { "#{@event.event_name}タイムテーブル" } %>

<div class="container">
    <div class="row">
    	<%= render 'events/event-header', event: @event, event_users: @event_users %>
    	<div class="panel panel-default">
    		<div class="panel-body">
		    	<div class="form-header text-center">
		            <h2 class="form-header-title">
		            	<%= @event.event_name %>タイムテーブル</h2>
		        </div>
				<div class="table-responsive">
					<table class="table table-bordered" style="table-layout:fixed;">
						<thead>
							<tr class="info">
								<th class="active" style="width:44px;">時間</th>
								<th class="active" style="width:100px;">曲名</th>
								<th class="active" style="width:100px;">アーティスト名</th>
								<% @parts.each do |part| %>
									<th class="active" style="width:80px;"><%= part.part_name %></th>
								<% end %>
							</tr>
						</thead>
						<tbody>
							<% n = 0 %> <!-- タイムテーブル時間設定のための初期値設定 -->
							<% @musics.each do |music| %>
							<tr>
								<td>
									<div>
									<%= (@event.start_time + 600 * n ).to_s(:time) %>
									<% n = n + 1 %>
									</div>
								</td>
								<th>
									<div>
									<%= link_to "#{music.title}", event_music_path(@event.friendly_url, music.id) %>
									</div>
								</th>
								<td>
									<%= music.artist %>
								</td>
								<% @parts.each do |part| %>
									<!-- パートが不要な時 -->
									<% if @entry_tables.find_by(music_id: music, part_id: part)&.requirement_status == "不要" %>
									<td>　</td>
									<!-- エントリーステータスが必須または任意の時 -->
									<% else %>
										<!-- 楽曲にユーザーがエントリーしていない時 -->
										<% if @entry_tables.find_by(music_id: music, part_id: part)&.event_user_id == nil %>
											<td>　</td>
										<!-- 楽曲にエントリーしているユーザーが本人の時 -->
										<% elsif @entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user == current_user %>
											<td class="danger">
												<%= link_to "#{@entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name}", user_path(@entry_tables.find_by(music_id: music, part_id: part).event_user.user) %>
											</td>
										<!-- 楽曲にユーザーがエントリーしている時 -->
										<% else %>
											<td>
											<%= link_to "#{@entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name}", user_path(@entry_tables.find_by(music_id: music, part_id: part).event_user.user) %>
											</td>
										<% end %>
									<% end %>
								<% end %>
								</tr>
							<% end %>
						</tbody>
					</table>
					<%= hidden_field_tag :event_id, @event.id %>

					<div class="col-xs-12 clearfix">
						<div class="panel panel-info">
							<div class="panel-heading">
								<h4 class="panel-title">注意事項</h4>
							</div>
							<div class="panel-body">
								<h4>イベント当日に関する注意</h4>
								・セッション参加3つのルール(①怪我をしないさせない　②転換演奏込み10分　③貴重品の管理は自己責任)は全員必ず守りましょう！<br>
								・機材置き場には限りがございますので、可能な限り荷物は少なめにお願いいたします。<br>
								・最初の受付時にイベント参加費(<%= @event.performance_fee %>円 or <%= @event.visit_fee %>円)と打ち上げ参加費(<%= @event.after_party.party_fee %>円)を合わせて徴収させていただきますので事前に用意をお願いします。<br>
								・セッティング完了後の音出し厳禁！！円滑な進行のためにもご協力お願いいたします。<br>
								<br>
								<%= link_to event_party_path(@event.friendly_url), class:"btn btn-lg btn-warning pull-right" do %>
									<i class="fas fa-beer icon_custom,"></i> 打ち上げ詳細
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>