config/routes.rb
Rails.application.routes.draw do
	devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
	devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
    }

    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    post '/callback' => 'linebot#callback'
    get 'users/twitter_new' => 'users#twitter_new', as: 'user_twitter_new'
    patch 'users/twitter_update/:id' => 'users#twitter_update', as: 'user_twitter_update'
    resources :users, only: [:show, :edit, :update]
    resources :events, only: [:show, :index] do
        get '/timetable' => 'events#timetable', as: 'timetable'
        get '/confirm' => 'events#confirm', as: 'confirm'
        get '/afterparty' => 'after_parties#show', as: 'party'
        resources :event_users, only: [:index, :create, :update, :destroy]
        resources :entry_tables, only: [:update, :destroy]
        post 'musics/new_confirm' => 'musics#new_confirm', as: 'music_new_confirm'
        patch 'musics/:id/edit_confirm' => 'musics#edit_confirm', as: 'music_edit_confirm'
        resources :musics, except: [:index] do
            resources :music_comments, only: [:create, :destroy]
            post '/lyrics/new_confirm' => 'lyrics#new_confirm', as: 'lyric_new_confirm'
            patch '/lyrics/:id/edit_confirm' => 'lyrics#edit_confirm', as: 'lyric_edit_confirm'
            patch '/lyrics/select_confirm' => 'lyrics#select_confirm', as: 'lyric_select_confirm'
            patch '/lyrics/select' => 'lyrics#select', as: 'lyric_select'
            resources :lyrics, only: [:new, :create, :edit, :update, :destroy]
        end
        post 'event_threads/confirm' => 'event_threads#confirm', as: 'threads_confirm'
        resources :event_threads, only: [:new, :create, :show, :update, :destroy] do
            resources :event_thread_comments, only: [:create, :destroy]
        end
    end

    namespace :admin do
      root 'homes#top'
    end

    namespace :admin do
      post 'events/new_confirm' => 'events#new_confirm', as: 'new_confirm'
      resources :events do
        get '/timetable' => 'events#timetable', as: 'timetable'
        patch '/timetable/releace' => 'events#timetable_releace', as: 'timetable_releace'
        patch '/timetable/sort' => 'events#sort'
        patch 'edit_confirm' => 'events#edit_confirm', as: 'edit_confirm'
        resources :entry_tables, only: [:update]
        resources :event_users, only: [:index, :update, :destroy]
      end
    end

    namespace :admin do
      resources :users, only: [:index, :show, :edit, :update]
    end
end

app/models/music.rb
class Music < ApplicationRecord
	has_many :music_comments, dependent: :destroy
	has_many :entry_tables, dependent: :destroy
	belongs_to :event
	acts_as_list scope: :event
	belongs_to :user
	belongs_to :lyric, optional: true #optional: trueでnilを許可
	accepts_nested_attributes_for :entry_tables

	validates :title, presence: true
	validates :artist, presence: true
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :show_header, only: [:new, :new_confirm, :show, :edit, :edit_confirm]
  def show_header
    @event = Event.friendly.find(params[:event_id])
    @event_users = EventUser.where(event_id: @event)
  end

  def new
    @music = Music.new
    @entry_table = @music.entry_tables.build
    @parts = Part.where(event_id: @event.id).order(:id)
  end

  def new_confirm
    @music = Music.new(music_params)
    @parts = Part.where(event_id: @event.id).order(:id)
    if @music.invalid?
      error =''
      @music.errors.full_messages.each do |message|
      error += message + '<br />'
      end
      @event = Event.friendly.find(params[:event_id])
      redirect_to new_event_music_path(@event), notice: error
    end
  end

  def create
    @music = Music.new(music_params)
    @music.establishment_count = @music.event.parts.count
    @music.save
    @music.establishment_count = @music.entry_tables.where(requirement_status: "必須" ,event_user_id: nil).count
    @music.save
    calculate_level(5)
    flash[:success] = "#{@music.title}を追加しました！"
    redirect_to event_music_path(@music.event.friendly_url, @music)
  end

  def show
    @now = Time.current
    @music = Music.find(params[:id])
    @entry_tables = EntryTable.where(music_id: @music)
    @music_comments = MusicComment.where(music_id: @music)
    @parts = Part.where(event_id: @event.id).order(:id)
    if EventUser.find_by(event_id: @event, user_id: current_user).presence
      @music_comment = MusicComment.new
    end
  end

  def edit
    @music = Music.find(params[:id])
    @entry_table = @music.entry_tables.all
    @parts = Part.where(event_id: @event.id).order(:id)
  end

  def edit_confirm
    @music = Music.find(params[:id])
    @parts = Part.where(event_id: @event.id).order(:id)
    @music.attributes = music_params
    render :edit if @music.invalid?
  end

  def update
    @music = Music.find(params[:id])
    if @music.update!(music_params)
      @music.establishment_count = @music.entry_tables.where(requirement_status: "必須" ,event_user_id: nil).count
      @music.save
      flash[:success] = "#{@music.title}を更新しました！"
      redirect_to event_music_path(@music.event.friendly_url, @music)
    else
      @event = Event.friendly.find(params[:event_id])
      @entry_table = @music.entry_tables.all
      @parts = Part.where(event_id: @event.id).order(:id)
      render "edit"
    end
  end

  def destroy
    music = Music.find(params[:id])
    music.destroy
    calculate_level(-5)
    flash[:danger] = "#{music.title}を削除しました！"
    redirect_to event_path(music.event.friendly_url)
  end

  def calculate_level(exp)
    if exp < 0
      current_user.level_up?(exp)
      flash[:info] = "楽曲削除 #{exp.to_i}pt"
    elsif current_user.level_up?(exp)
      flash[:info] = "楽曲追加 #{exp.to_i}pt Get! Level UP!!"
    else
      flash[:info] = "楽曲追加 #{exp.to_i}pt Get!"
    end
  end

  private
  def music_params
    params.require(:music).permit(:event_id, :title, :artist, :music_url, :remarks, :user_id, :lyric_id,
     entry_tables_attributes: [:id, :event_user_id, :music_id, :part_id, :recruitment_status, :requirement_status])
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_musicentrytable.html.erb
<table class="table table-bordered" style="table-layout:fixed;">
    <tr>
        <% parts.each do |part| %>
            <th class="active" style="width:80px;"><%= part.part_name %></th>
        <% end %>
    </tr>
    <tr>
        <% parts.each do |part| %>
        <td>
            <!-- パートが不要な時 -->
            <% if entry_tables.find_by(music_id: music, part_id: part)&.requirement_status == "不要" %>
            <!-- 空欄 -->
            <!-- エントリーステータスが必須の時 -->
            <% elsif entry_tables.find_by(music_id: music.id, part_id: part.id)&.requirement_status == "必須" %>
                <!-- ユーザーがログインしている時 -->
                <% if user_signed_in? %>
                    <!-- 楽曲にユーザーがエントリーしていない時 -->
                    <% if entry_tables.find_by(music_id: music, part_id: part)&.event_user_id == nil %>
                        <!-- ユーザーがイベントに参加している時 -->
                        <% if @event_users.where(user_id: current_user.id).present? %>
                            <!-- ユーザーが見学参加の場合 -->
                            <% if event_users.find_by(user_id: current_user.id).part_table.part_name == "見学" %>
                                <a class="link" data-toggle="modal" data-target="#observeModal">エントリー</a>
                            <% elsif event.entry_start_time <= now && now < event.entry_finish_time %>
                                <%= link_to "エントリー", event_entry_table_path(event.friendly_url, music_id: music.id, part_id: part.id, name: "entry"), method: :patch %>
                            <% elsif event.entry_start_time > now %>
                                <a class="link" data-toggle="modal" data-target="#notentryModal">エントリー</a>
                            <% elsif now >= event.entry_finish_time %>
                                受付終了
                            <% end %>
                        <!-- ユーザーがイベントに参加していない時 -->
                        <% else %>
                            <% if event.entry_start_time <= now && now < event.entry_finish_time %>
                                <a class="link" data-toggle="modal" data-target="#attendanceModal">エントリー</a>
                            <% elsif event.entry_start_time > now %>
                                <a class="link" data-toggle="modal" data-target="#notentryModal">エントリー</a>
                            <% elsif now >= event.entry_finish_time %>
                                受付終了
                            <% end %>
                        <% end %>
                    <!-- 楽曲にユーザーがエントリーしている時 -->
                    <% else %>
                        <%= link_to "#{entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name}", user_path(entry_tables.find_by(music_id: music, part_id: part).event_user.user) %>
                        <!-- 楽曲にエントリーしているユーザーが本人の時 -->
                        <% if entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user == current_user %>
                            <%= link_to event_entry_table_path(event, music_id: music, part_id: part, name: "cancel"), method: :patch, data: {confirm: "本当にエントリーを取り消してもよろしいですか？"} do %>
                                <i class="fas fa-times-circle"></i>
                            <% end %>
                        <% end %>
                    <% end %>
                <!-- ユーザーがログインしていない時 -->
                <% else %>
                    <!-- 楽曲にユーザーがエントリーしていない時 -->
                    <% if entry_tables.find_by(music_id: music, part_id: part)&.event_user_id == nil %>
                        <% if now < event.entry_finish_time %>
                            <a class="link" data-toggle="modal" data-target="#loginModal">エントリー</a>
                        <% elsif now >= event.entry_finish_time %>
                            受付終了
                        <% end %>
                    <!-- 楽曲にユーザーがエントリーしている時 -->
                    <% else %>
                        <%= entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name %>
                    <% end %>
                <% end %>
            <!-- エントリーステータスが任意の時 -->
            <% elsif entry_tables.find_by(music_id: music.id, part_id: part.id)&.requirement_status == "任意" %>
                <% if user_signed_in? %>
                    <!-- 楽曲にユーザーがエントリーしていない時 -->
                    <% if entry_tables.find_by(music_id: music, part_id: part)&.event_user_id == nil %>
                        <!-- ユーザーがイベントに参加している時 -->
                        <% if @event_users.where(user_id: current_user.id).present? %>
                            <!-- ユーザーが見学参加の場合 -->
                            <% if event_users.find_by(user_id: current_user.id).part_table.part_name == "見学" %>
                                <a class="link" data-toggle="modal" data-target="#observeModal">(エントリー)</a>
                            <% elsif event.entry_start_time <= now && now < event.entry_finish_time %>
                                <%= link_to "(エントリー)", event_entry_table_path(event.friendly_url, music_id: music.id, part_id: part.id, name: "entry"), method: :patch %>
                            <% elsif event.entry_start_time > now %>
                                <a class="link" data-toggle="modal" data-target="#notentryModal">(エントリー)</a>
                            <% elsif now >= event.entry_finish_time %>
                                受付終了
                            <% end %>
                        <!-- ユーザーがイベントに参加していない時 -->
                        <% else %>
                            <% if event.entry_start_time <= now && now < event.entry_finish_time %>
                                <a class="link" data-toggle="modal" data-target="#attendanceModal">(エントリー)</a>
                            <% elsif event.entry_start_time > now %>
                                <a class="link" data-toggle="modal" data-target="#notentryModal">(エントリー)</a>
                            <% elsif now >= event.entry_finish_time %>
                                受付終了
                            <% end %>
                        <% end %>
                    <!-- 楽曲にユーザーがエントリーしている時 -->
                    <% else %>
                        <%= link_to "#{entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name}", user_path(entry_tables.find_by(music_id: music, part_id: part).event_user.user) %>
                        <!-- 楽曲にエントリーしているユーザーが本人の時 -->
                        <% if entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user == current_user %>
                            <%= link_to event_entry_table_path(event, music_id: music, part_id: part, name: "cancel"), method: :patch, data: {confirm: "本当にエントリーを取り消してもよろしいですか？"} do %>
                                <i class="fas fa-times-circle"></i>
                            <% end %>
                        <% end %>
                    <% end %>
                <!-- ユーザーがログインしていない時 -->
                <% else %>
                    <!-- 楽曲にユーザーがエントリーしていない時 -->
                    <% if entry_tables.find_by(music_id: music, part_id: part)&.event_user_id == nil %>
                        <% if now < event.entry_finish_time %>
                            <a class="link" data-toggle="modal" data-target="#loginModal">(エントリー)</a>
                        <% elsif now >= event.entry_finish_time %>
                            受付終了
                        <% end %>
                    <!-- 楽曲にユーザーがエントリーしている時 -->
                    <% else %>
                        <%= entry_tables.find_by(music_id: music, part_id: part)&.event_user&.user&.name %>
                    <% end %>
                <% end %>
            <% end %>
        </td>
        <% end %>
    </tr>
</table>
<%= render 'homes/modal_signin' %>
<%= render 'entry_tables/modal_notentry', event: event %>
<%= render 'entry_tables/modal_observe' %>
<%= render 'events/modal_attendance', event: event %>

app/views/musics/edit.html.erb
<% content_for(:html_title) { "#{@music.title}編集" } %>
<div class="container">
    <div class="row">
    	<%= render 'events/event-header', event: @event, event_users: @event_users %>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-user style-1 rounded has-shadow-1">
                <div class="form-header">
                    <div class="form-header text-center">
                        <h2 class="form-header-title">楽曲編集</h2>
                    </div>
                    <%= form_for [@event,@music], url:event_music_edit_confirm_path(@event, @music) do |f| %>
                    <%= render 'layouts/error_messages', model: f.object %>
                    <table class="table table-bordered">
                      	<tbody>
                            <tr>
	                            <th class="active">曲タイトル</th>
	                            <td><%= f.text_field :title, size: 70, :placeholder => "曲名" %></td>
	                        </tr>
	                        <tr>
	                        	<th class="active">アーティスト名</th>
	                        	<td><%= f.text_field :artist, size: 70, :placeholder => "アーティスト名" %></td>
	                        </tr>
	                        <tr>
	                        	<th class="active">youtube</th>
	                        	<td><%= f.text_field :music_url, size: 70, :placeholder => "https://www.youtube.com/からはじまるURLを入力してください" %></td>
	                        </tr>
	                        <tr>
	                        	<th class="active">パート</th>
                        		<td>
		                        	<table class="table table-bordered">
			                          	<tbody>
				                            <tr>
					                            <th class="active">
					                            パート
					                        	</th>
					                        	<% @parts.each do |part| %>
					                        	<td class="active">
					                        		<%= part.part_name %>
					                        	</td>
					                        	<% end %>
					                        </tr>
					                       	<tr>
					                       		<th>
					                       			必須<br>
					                       			任意<br>
					                       			不要<br>
					                            </th>
					                        	<%= f.fields_for :entry_tables do |entry_table| %>
					                        	<td>
													<%= entry_table.radio_button :requirement_status, :必須 %><br>
													<%= entry_table.radio_button :requirement_status, :任意 %><br>
													<%= entry_table.radio_button :requirement_status, :不要 %><br>
												</td>
												<% end %>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
							<tr>
								<th class="active">備考</th>
								<td><%= f.text_area :remarks, size: "20x5", class: "form-control" %></td>
							</tr>
								<%= f.hidden_field :event_id, :value => @event.id %>
						</tbody>
					</table>
						<%= f.submit "確認画面へ", class: "btn btn-lg btn-block btn-primary" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/musics/edit_confirm.html.erb
<% content_for(:html_title) { "#{@music.title}編集" } %>
<div class="container">
    <div class="row">
		<%= render 'events/event-header', event: @event, event_users: @event_users %>
		<div class="col-md-8 col-md-offset-2">
		    <div class="form-user style-1 rounded has-shadow-1">
		        <div class="form-header">
		            <div class="form-header text-center">
		                <h2 class="form-header-title">楽曲編集</h2>
		            </div>
		            <%= form_for [@event,@music] do |f| %>
		            <%= render 'layouts/error_messages', model: f.object %>
		            <table class="table table-bordered">
		              	<tbody>
		                    <tr>
		                        <th class="active">曲タイトル</th>
		                        <td><%= @music.title %></td>
		                        <%= f.hidden_field :title, :value => @music.title %>
		                    </tr>
		                    <tr>
		                    	<th class="active">アーティスト名</th>
		                    	<td><%= @music.artist %></td>
		                    	<%= f.hidden_field :artist, :value => @music.artist %>
		                    </tr>
		                    <% if @music.music_url.presence %>
			                    <tr>
			                    	<th class="active">youtube</th>
	                    			<td><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @music.music_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
	                    				<%= f.hidden_field :music_url, :value => @music.music_url %>
	                    			</td>
			                    </tr>
		                    <% end %>
		                    <tr>
		                    	<th class="active">パート</th>
		                		<td>
		                        	<table class="table table-bordered">
			                          	<tbody>
				                            <tr>
					                            <th class="active">
					                            	パート
					                            </th>
					                            <% @parts.each do |part| %>
					                            <th class="active"><%= part.part_name %></th>
					                            <% end %>
					                        </tr>
					                        <tr>
					                        	<th class="active">
					                            	ステータス
					                            </th>
					                            <!-- パラメーター取得のための初期値設定 -->
					                            <% n = 0 %>
					                            <%= f.fields_for :entry_tables do |entry_table| %>
						                            <td>
						                            	<!-- パラメータ内に変数を置く時はstrings型じゃないと取ってこれないので変換 -->
						                            	<% n = n.to_s %>
					                            		<% if params[:music][:entry_tables_attributes][n][:requirement_status] == "不要" %>
					                            		<% elsif params[:music][:entry_tables_attributes][n][:requirement_status] == "任意" %>
					                            		(任意)
					                            		<% else %>
					                            			<%= params[:music][:entry_tables_attributes][n][:requirement_status] %>
					                            		<% end %>
					                            		<%= entry_table.hidden_field :requirement_status, :value => params[:music][:entry_tables_attributes][n][:requirement_status] %>
														<!-- strings型のままだと数字が足せないのでinteger型に変換 -->
														<% n = n.to_i + 1 %>
													</td>
												<% end %>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
							<tr>
								<th class="active">備考</th>
								<td><%= @music.remarks %></td>
		                    	<%= f.hidden_field :remarks, :value => @music.remarks %>
							</tr>
						</tbody>
					</table>
						<%= f.submit "この内容で編集する", class: "btn btn-lg btn-block btn-primary" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/musics/new.html.erb
<% content_for(:html_title) { "楽曲追加" } %>
<div class="container">
    <div class="row">
		<%= render 'events/event-header', event: @event, event_users: @event_users %>
		<div class="col-md-8 col-md-offset-2">
		    <div class="form-user style-1 rounded has-shadow-1">
		        <div class="form-header">
		            <div class="form-header text-center">
		                <h2 class="form-header-title">楽曲追加</h2>
		            </div>
		            <%= form_for [@event,@music], url: event_music_new_confirm_path(@event, @music) do |f| %>
		            <%= render 'layouts/error_messages', model: f.object %>
		            <table class="table table-bordered">
		              	<tbody>
		                    <tr>
		                        <th class="active">曲タイトル</th>
		                        <td><%= f.text_field :title, size: 70, :placeholder => "曲名" %></td>
		                    </tr>
		                    <tr>
		                    	<th class="active">アーティスト名</th>
		                    	<td><%= f.text_field :artist, size: 70, :placeholder => "アーティスト名" %></td>
		                    </tr>
		                    <tr>
		                    	<th class="active">youtube</th>
		                    	<td><%= f.text_field :music_url, size: 70, :placeholder => "https://www.youtube.com/からはじまるURLを入力してください" %></td>
		                    </tr>
		                    <tr>
		                    	<th class="active">パート</th>
		                		<td>
		                        	<table class="table table-bordered">
			                          	<tbody>
				                            <tr>
					                            <th class="active">
					                            	パート
					                            </th>
					                            <% @parts.each do |part| %>
					                            <th class="active"><%= part.part_name %></th>
					                            <% end %>
					                        </tr>
					                        <tr>
					                        	<th>
					                            	必須<br>
					                            	<br>
					                            	任意<br>
					                            	<br>
					                            	不要<br>
					                            </th>
					                            <% @parts.each do |part| %>
					                            <td>
						                        	<%= f.fields_for :entry_tables do |entry_table| %>
														<%= entry_table.radio_button :requirement_status, :必須, checked: true %><br>
														<br>
														<%= entry_table.radio_button :requirement_status, :任意 %><br>
														<br>
														<%= entry_table.radio_button :requirement_status, :不要 %>
														<%= entry_table.hidden_field :music_id, :value => @music.id %>
														<%= entry_table.hidden_field :part_id, :value => part.id %>
														<%= entry_table.hidden_field :recruitment_status, :value => "募集中" %>
													<% end %>
												</td>
												<% end %>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
							<tr>
								<th class="active">備考</th>
								<td><%= f.text_area :remarks, size: "20x5", class: "form-control" %></td>
							</tr>
								<%= f.hidden_field :event_id, :value => @event.id %>
								<%= f.hidden_field :user_id, :value => current_user.id %>
						</tbody>
					</table>
						<%= f.submit "確認画面へ", class: "btn btn-lg btn-block btn-primary" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/musics/show.html.erb
<% content_for(:html_title) { "#{@music.title}" } %>
<div class="container">
    <div class="row">
        <%= render 'events/event-header', event: @event, event_users: @event_users %>
        <h2><%= @music.title %>の楽曲情報
            <% if user_signed_in? %>
                <% if @event_users.where(user_id: current_user.id).presence %>
                <%= link_to "編集する", edit_event_music_path(@music.event_id, @music.id), class: "btn btn-md btn-warning pull-right" %>
                <% end %>
                <% if @music.user_id == current_user.id %>
                    <%= link_to "削除する",event_music_path(@music.event_id, @music.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-md btn-danger pull-right" %>
                <% end %>
            <% end %>
        </h2>
        <div class="col-xs-8">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th class="active">アーティスト名</th>
                    <td><%= @music.artist %></td>
                </tr>
                <% if @music.music_url.presence %>
                <tr>
                    <th class="active">youtube</th>
                    <td><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @music.music_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </td>
                </tr>
                <% end %>
                <tr>
                    <th class="active">成立ステータス</th>
                    <td><% if @music.establishment_count == 0 %>
                            成立
                        <% elsif @music.event.finish_time < Time.current %>
                            募集終了
                        <% elsif @music.establishment_count > 0 %>
                            募集中
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th class="active">追加日時 </th>
                    <td><%= @music.created_at.to_s(:datetime) %> by <%= link_to "#{@music.user.name}", user_path(@music.user) %></td>
                </tr>
                <tr>
                    <th class="active">備考</th>
                    <td><%= @music.remarks %></td>
                </tr>
            </tbody>
        </table>
        </div>
        <div class="col-xs-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    パート分け
                    <% if @music.lyric_id.present? %> (<%= @music.lyric.user.name %>さん作成)<% end %>
                    <% if user_signed_in? %>
                        <% if @event_users.where(user_id: current_user.id).presence %>
                            <%= link_to "歌詞登録", new_event_music_lyric_path(@event.friendly_url, @music), class:"pull-right" %>
                        <% end %>
                    <% end %>
                </div>
                <div class="panel-body">
                    <div style="width:100% ; height:410px; overflow:auto;">
                        <% if @music.lyric_id.nil? %>
                            歌詞が登録されていません
                        <% else %>
                            <%= sanitize @music.lyric.lyric, attributes:  %w(id class href) %>
                            <% if user_signed_in? %>
                                <% if @music.lyric.user_id == current_user.id %>
                                    <%= link_to "パート分けを編集する", edit_event_music_lyric_path(@event.friendly_url, @music, @music.lyric_id), class:"pull-right" %>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <%= render 'musics/musicentrytable', parts: @parts, event: @event, entry_tables: @entry_tables, event_users: @event_users, music: @music, now: @now %>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">コメント<span class="h4">(<%= @music_comments.count %>件)</span></h3>
            </div>
            <div class="panel-body">
                <% if user_signed_in? %>
                    <% @music_comments.each do |music_comment| %>
                        <div class="voice-img" >
                            <%= attachment_image_tag music_comment.user, :image, format: 'jpeg', fallback: "no_image.jpg", size:'60x60', class:"img-circle" %><br>
                            <div class="voice-img-description">
                                <%= link_to "#{music_comment.user.name}", user_path(music_comment.user_id) %>
                            </div>
                        </div>
                        <div class="voice">
                            <div class="voice-text">
                               <%= music_comment.comment %><br>
                            </div>
                            <div class="comment-datetime">
                                <% if music_comment.user == current_user %>
                                    <%= link_to "削除", event_music_music_comment_path(@event,@music,music_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
                                <% end %>
                                <%= music_comment.created_at.to_s(:datetime) %>
                            </div>
                        </div>
                        <!-- AI機能実装 -->
                        <span class="comment-score"><% music_comment&.score %></span>
                        <!-- AI機能実装終了 -->
                    	<br>
                    <% end %>
                    <% if @event_users.where(user_id: current_user.id).presence %>
                        <%= form_for [@event, @music, @music_comment] do |f| %>
                        <%= render 'layouts/error_messages', model: f.object %>
                            <div class="row">
                                <div class="col-sm-12">
                                    <%= f.text_area :comment, rows:'5', class: "form-control", placeholder: "コメントをここに" %>
                                </div>
                            </div>
                            <%= f.submit "送信する", class: "btn btn-lg btn-primary pull-right" %>
                        <% end %>
                    <% end %>
                <% else %>
                    ※コメントの閲覧はログイン後に行うことができます。
                <% end %>
            </div>
        </div>
    </div>
</div>